import type { TicketDetailDto, TicketListItemDto } from './dto/ticket.dto';

/**
 * ข้อมูลตัวอย่างสำหรับ API doc และให้ frontend เริ่มต่อได้ก่อนมีฐานข้อมูล
 * ครอบคลุมสถานะครบ 7 ค่า และ SLA ครบ 4 ค่า
 */

export const MOCK_TICKETS: TicketListItemDto[] = [
  {
    id: 1038,
    ticket_no: 'AIDC-LOG-202608-0038',
    ticket_type: 'incident',
    subject: 'WMS ເຂົ້າລະບົບບໍ່ໄດ້ທັງສາງ',
    status: 'new',
    pending_reason: null,
    priority: 'P1',
    support_tier: 1,
    company: { id: 7, code: 'AIDC-LOG', name_th: 'ເອໄອດີຊີ ໂລຈິສຕິກ' },
    department: { id: 22, name: 'ສາງສິນຄ້າ' },
    category: { id: 78, name_th: 'ລະບົບສາງສິນຄ້າ (WMS)' },
    requester: { id: 145, full_name: 'ສົມຊາຍ ກິດຕິວັດ' },
    assignee: null,
    sla: {
      clock_mode: 'calendar_24x7',
      status: 'breached',
      remaining_minutes: -72,
      remaining_unit: 'calendar_minutes',
      resolution_due_at: '2026-08-31T11:15:00+07:00',
      is_response_breached: true,
      is_resolution_breached: true,
      pending_duration_minutes: 0,
    },
    reopen_count: 0,
    comment_count: 1,
    attachment_count: 0,
    created_at: '2026-08-31T07:15:00+07:00',
    updated_at: '2026-08-31T12:27:00+07:00',
  },
  {
    id: 1042,
    ticket_no: 'AIDC-LOG-202608-0042',
    ticket_type: 'incident',
    subject: 'ເຄື່ອງສະແກນບາໂຄດສາງ 2 ອ່ານບໍ່ຕິດ',
    status: 'in_progress',
    pending_reason: null,
    priority: 'P2',
    support_tier: 1,
    company: { id: 7, code: 'AIDC-LOG', name_th: 'ເອໄອດີຊີ ໂລຈິສຕິກ' },
    department: { id: 22, name: 'ສາງສິນຄ້າ' },
    category: { id: 79, name_th: 'ເຄື່ອງສະແກນບາໂຄດ/ເຄື່ອງພິມສະຫຼາກ' },
    requester: { id: 145, full_name: 'ສົມຊາຍ ກິດຕິວັດ' },
    assignee: { id: 88, full_name: 'ພູວົງ ສີສຸກ' },
    sla: {
      clock_mode: 'business_hours',
      status: 'at_risk',
      remaining_minutes: 42,
      remaining_unit: 'business_minutes',
      resolution_due_at: '2026-08-31T17:15:00+07:00',
      is_response_breached: false,
      is_resolution_breached: false,
      pending_duration_minutes: 0,
    },
    reopen_count: 0,
    comment_count: 3,
    attachment_count: 2,
    created_at: '2026-08-31T09:15:00+07:00',
    updated_at: '2026-08-31T11:02:00+07:00',
  },
  {
    id: 1031,
    ticket_no: 'AIDC-LOG-202608-0031',
    ticket_type: 'service_request',
    subject: 'ຂໍສິດເຂົ້າເຖິງໂຟນເດີງົບປະມານ 2570',
    status: 'pending_user',
    pending_reason: 'approval',
    priority: 'P4',
    support_tier: 1,
    company: { id: 7, code: 'AIDC-LOG', name_th: 'ເອໄອດີຊີ ໂລຈິສຕິກ' },
    department: { id: 30, name: 'ການເງິນ' },
    category: { id: 55, name_th: 'ຂໍສິດເຂົ້າເຖິງລະບົບ' },
    requester: { id: 210, full_name: 'ກັນລະຍາ ຈະເລີນ' },
    assignee: { id: 91, full_name: 'ສົມຍິງ ຈັນທະວົງ' },
    sla: {
      clock_mode: 'business_hours',
      status: 'paused',
      remaining_minutes: null,
      remaining_unit: 'business_minutes',
      // นาฬิกายังไม่เริ่มเดินเพราะรออนุมัติครบก่อน (clock_start_event = after_approval)
      clock_started_at: null,
      resolution_due_at: null,
      is_response_breached: false,
      is_resolution_breached: false,
      pending_reason: 'approval',
      pending_duration_minutes: 0,
    },
    reopen_count: 0,
    comment_count: 4,
    attachment_count: 1,
    created_at: '2026-08-28T14:20:00+07:00',
    updated_at: '2026-08-29T09:10:00+07:00',
  },
  {
    id: 1027,
    ticket_no: 'AIDC-LOG-202608-0027',
    ticket_type: 'incident',
    subject: 'GPS ລົດທະບຽນ 82-4471 ບໍ່ສົ່ງພິກັດ ລໍຖ້າອາໄຫຼ່ຈາກຜູ້ໃຫ້ບໍລິການ',
    status: 'pending_user',
    pending_reason: 'vendor',
    priority: 'P2',
    support_tier: 3,
    company: { id: 7, code: 'AIDC-LOG', name_th: 'ເອໄອດີຊີ ໂລຈິສຕິກ' },
    department: { id: 24, name: 'ປະຕິບັດການຂົນສົ່ງ' },
    category: { id: 82, name_th: 'GPS / ລະບົບຕິດຕາມລົດ' },
    requester: { id: 220, full_name: 'ສູນຄວບຄຸມຂົນສົ່ງ' },
    assignee: { id: 88, full_name: 'ພູວົງ ສີສຸກ' },
    sla: {
      clock_mode: 'business_hours',
      status: 'paused',
      remaining_minutes: null,
      remaining_unit: 'business_minutes',
      resolution_due_at: '2026-09-03T10:00:00+07:00',
      is_response_breached: false,
      is_resolution_breached: false,
      paused_at: '2026-08-29T13:40:00+07:00',
      pending_reason: 'vendor',
      pending_duration_minutes: 1080,
    },
    reopen_count: 0,
    comment_count: 6,
    attachment_count: 2,
    created_at: '2026-08-27T08:40:00+07:00',
    updated_at: '2026-08-29T13:40:00+07:00',
  },
  {
    id: 1024,
    ticket_no: 'AIDC-TECH-202608-0024',
    ticket_type: 'incident',
    subject: 'Wi-Fi ຊັ້ນ 3 ອາຄານ B ຫຼຸດເປັນຊ່ວງ',
    status: 'resolved',
    pending_reason: null,
    priority: 'P3',
    support_tier: 2,
    company: { id: 5, code: 'AIDC-TECH', name_th: 'ເອໄອດີຊີ ເທັກ' },
    department: { id: 50, name: 'ພັດທະນາລະບົບ' },
    category: { id: 33, name_th: 'ເຄືອຂ່າຍ / Wi-Fi' },
    requester: { id: 230, full_name: 'ທີມພັດທະນາລະບົບ' },
    assignee: { id: 90, full_name: 'ທະນູ ວັດທະນາ' },
    sla: {
      clock_mode: 'business_hours',
      status: 'on_track',
      remaining_minutes: null,
      remaining_unit: 'business_minutes',
      resolution_due_at: '2026-08-28T16:00:00+07:00',
      is_response_breached: false,
      is_resolution_breached: false,
      pending_duration_minutes: 0,
    },
    reopen_count: 1,
    comment_count: 8,
    attachment_count: 0,
    created_at: '2026-08-26T10:05:00+07:00',
    updated_at: '2026-08-28T15:12:00+07:00',
  },
];

export function mockDetail(): TicketDetailDto {
  const base = MOCK_TICKETS[1]!;
  return {
    ...base,
    description:
      'ເຄື່ອງສະແກນບາໂຄດ 3 ໜ່ວຍທີ່ໂຊນຮັບສິນຄ້າສາງ 2 ອ່ານບໍ່ຕິດຕັ້ງແຕ່ເຊົ້າ ເຮັດໃຫ້ຮັບເຄື່ອງເຂົ້າລະບົບບໍ່ໄດ້ ມີລົດລໍຖ້າຄິວ 4 ຄັນ',
    impact: 'department',
    urgency: 'high',
    channel: 'portal',
    // สิทธิ์ชุดนี้เป็นของ agent ที่รับผิดชอบเรื่องนี้อยู่
    can: {
      update: true,
      assign: true,
      claim: false,
      change_status: true,
      change_priority: true,
      request_priority_review: false,
      comment: true,
      comment_internal: true,
      attach: true,
      close: false,
      reopen: false,
      cancel: true,
      set_workaround: true,
      change_tier: true,
      delete: false,
    },
  };
}
